Feature auv 0002 update controllers
auvaraksin/online-advertising-shop pull request #11
Opened 2022-11-20 21:34 UTC by auvaraksin

Не создаются таблицы в БД

2022-11-22 08:17 UTC, OlgaLugacheva requested changes

2022-11-22 08:17 UTC, OlgaLugacheva commented on src/main/java/ru/skypro/homework/entity/Ads.java
> +            name = "ads_id",
ну зачем вот эта приставка ads_ ? ведь и так понятно к какой таблице сущность относится

2022-11-22 08:17 UTC, OlgaLugacheva commented on src/main/java/ru/skypro/homework/service/AdsCommentService.java
> +public interface AdsCommentService {
почему тут все пусто? пора реализовывать логику

2022-11-22 08:17 UTC, OlgaLugacheva commented on src/main/java/ru/skypro/homework/service/AdsService.java
> +public interface AdsService {
пусто? мы ничего не будем делать с объявлениями?

2022-11-22 08:17 UTC, OlgaLugacheva commented on src/main/java/ru/skypro/homework/service/UserService.java
> +    void createUser(RegReqDto regReqDto);
создавать пользователя нам здесь не нужно, мы его через AuthService создаем
но получать, вероятно, будет нужно

2022-11-22 08:17 UTC, OlgaLugacheva commented on src/main/java/ru/skypro/homework/service/impl/UserServiceImpl.java
> +        logger.info("Method to create a new record " + user + " in the DB in table 'User' was invoked");
не надо

2022-11-22 18:29 UTC, auvaraksin commented on src/main/java/ru/skypro/homework/service/UserService.java
> +    void createUser(RegReqDto regReqDto);
Не совсем понимаю комментарий, т.к. данные пользователя должны попасть в БД. Без данного сервиса записать в БД невозможно.

2022-11-22 18:29 UTC, auvaraksin commented on src/main/java/ru/skypro/homework/service/impl/UserServiceImpl.java
> +        logger.info("Method to create a new record " + user + " in the DB in table 'User' was invoked");
Не надо что?

2022-11-23 03:56 UTC, OlgaLugacheva requested changes

2022-11-23 03:56 UTC, OlgaLugacheva commented on src/main/java/ru/skypro/homework/WebSecurityConfig.java
> +    }
если вам непонятно как использовать DaoAuthentifiactionProvider 
, то лучше его не использовать, нужно онимать, что вы делаете 
вместо этого используйте реализацию по умолчанию 

    @Bean
    public JdbcUserDetailsManager userDetailsService(DataSource dataSource) {
        return new JdbcUserDetailsManager(dataSource);
    }

2022-11-23 03:56 UTC, OlgaLugacheva commented on src/main/java/ru/skypro/homework/WebSecurityConfig.java
> +    private final UserDetailsService userDetailsService;
это убрать и добавить 
    @Autowired
    private DataSource dataSource;

2022-11-23 03:56 UTC, OlgaLugacheva commented on src/main/java/ru/skypro/homework/WebSecurityConfig.java
> +    }
убрать

2022-11-29 19:48 UTC, merged